project:
  type: website

website:
  title: "Machine Learning for Public Policy"
  navbar:
    logo: "/assets/ML4PP.png"
    left:
      - href: index.qmd
        text: Home
      - text: "Introduction"
        menu:
        - introduction.qmd
        - r-intro.qmd
        - python-intro.qmd
      - text: "Content"
        menu:
        - predictionpolicy.qmd 
        - classification.qmd
        - treebasedmodels.qmd
        - fairml.qmd
        - neuralNets.qmd
      - policyChallenge.qmd
    tools:
      - icon: github
        href: "https://github.com/lucasboh/ml4p-website-v2"
  body-footer: |
   <div class="footer">
      Copyright &copy; 2025 Michelle González Amador & Stephan Dietrich. All rights reserved.<br>
      [![GitHub](https://img.shields.io/badge/GitHub-Repository-blue?logo=github)](https://github.com/lucasboh/ml4p-website-v2)
    </div>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    highlight-style: github-dark

editor: visual


