project:
  type: website

website:
  title: "Machine Learning for Public Policy"
  navbar:
    logo: "/assets/ML4PP.png"
    left:
      - href: index.qmd
        text: Home
      - text: "Introduction"
        menu:
        - introduction.qmd
        - r-intro.qmd
        - python-intro.qmd
      - text: "Content"
        menu:
        - text: "Prediction Policy Problems"
          href: session_1.qmd
        - classification.qmd
        - treebasedmodels.qmd
        - fairml.qmd
        - neuralNets.qmd
      - text: "Collaborative Policy Challenge"
        menu:
        - text: "2024"
          href: policy-challenge-2024.qmd
        - text: "2025"
          href: policy-challenge-2025.qmd
      - text: "About"
        href: about.qmd
    tools:
      - icon: github
        href: "https://github.com/lucasboh/ml4p-website-v2"
  body-footer: |
   <div class="footer">
      Copyright &copy; 2025 Michelle González Amador & Stephan Dietrich. All rights reserved.<br>
      [![GitHub](https://img.shields.io/badge/GitHub-Repository-blue?logo=github)](https://github.com/lucasboh/ml4p-website-v2)
    </div>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    highlight-style: github-dark

editor: visual


