---
title: "Prediction Policy Problems: Linear Models and Lasso Regression"
format: html
---

## Introducing the Prediction Policy Framework

In the video-lecture below you'll be given a brief introduction to the prediction policy framework, and a primer on machine learning. Please take a moment to watch the 20 minute video.

{{< video https://youtu.be/sFbKe4O0tEQ >}}

Are you still wondering what the difference is between Machine Learning and Econometrics? Take a few minutes to watch the video below. 

{{< video https://youtu.be/gx_MBxMu0m4 >}}

After watching the videos, we have a practical exercise.

### Predicting social assistance beneficiaries 

A key problem in the design of Social Policies is the identification of people in need of social assistance.
Social policies usually work with tight budgets and limited fiscal space. To allocate resources efficiently, benefits need to be targeted to those who need them most. Yet, identifying needs isn’t easy and misclassifications can have severe and irreversible effects on people in need.

Think of a social protection programme that allocates food vouchers to families with children at risk of malnutrition, or a programme that establishes needs-based school grants. What happens when these limited and finite resources are given to people that could do without, and those who need them most are excluded from them?

In this block we'll work with real-world data from the country of Malawi to predict cash-transfer programme beneficiaries: People who live in poverty and need government assistance to make ends meet. The data comes from McBride and Nichol's (2018) paper [Retooling poverty targeting using out-of-sample validation and machine learning](https://elibrary.worldbank.org/doi/abs/10.1093/wber/lhw056).

**Discussion Points**

The points below are meant to help you think critically about why we're about to embark on a machine learning - targeting exercise.
<br>

<ul>
<li> Why is this a prediction policy problem? What would be a causal inference problem in this setting? Is it a regression or a classification problem? </li>
<li> Which variables and characteristics that we include in the prediction model can make a big difference?
    <ul>
    <li>Programmatically and conceptually, which type of characteristics do we want to consider for the prediction model?</li>
    <li>Technically, how do we select which variables to include in a prediction model? How is this different from a causal inference problem?</li>
    </ul>
</li>    
<li> What are the practical implications of the bias-variance tradeoff in this application? </li>
<li> What are potential risks of such a data driven targeting approach? </li>
</ul>

<br>

**If you'd like to learn more about Social Protection Policies, take a look at this video Alex has made for us with a brilliant summary of the field**

(Yes, more videos!)

{{< video https://youtu.be/Pn9DntDejKU >}}

## R Practical

You can download the dataset by clicking on the button below.

<button type="button" class="btn btn-primary" download="https://github.com/michelleg06/Machine-Learning-for-Public-Policy/blob/main/malawi.csv">Download Malawi.csv</button>
<br>

The script below is a step by step on how to go about coding a predictive model using a *linear regression*. Despite its simplicity and transparency, i.e. the ease with which we can interpret its results, a linear model is not without challenges in machine learning.


### 1. Preliminaries: working directory, libraries, data upload

```{r, message=FALSE}
rm(list = ls()) # this line cleans your Global Environment.
setwd("/Users/lucas/Documents/UNU-CDO/courses/ml4p/ml4p-website-v2/data") # set your working directory

# Libraries

# If this is your first time using R, you need to install the libraries before loading them. 
# To do that, you can uncomment the line that starts with install.packages(...) by removing the # symbol.    

#install.packages("dplyr", "tidyverse", "caret", "corrplot", "Hmisc", "modelsummary", "plyr", "gt", "stargazer", elasticnet")

library(dplyr) # core package for dataframe manipulation. Usually installed and loaded with the tidyverse, but sometimes needs to be loaded in conjunction to avoid warnings.
library(tidyverse) # a large collection of packages for data manipulation and visualisation.  
library(caret) # a package with key functions that streamline the process for predictive modelling 
library(corrplot) # a package to plot correlation matrices
library(Hmisc) # a package for general-purpose data analysis 
library(modelsummary) # a package to describe model outputs
library(skimr) # a package to describe dataframes
library(plyr) # a package for data wrangling
library(gt) # a package to edit modelsummary (and other) tables
library(stargazer) # a package to visualise model output

data_malawi <- read_csv("malawi.csv") # the file is directly read from the working directory/folder previously set

```
