<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.41">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Prediction Policy Problems: Linear Models and Lasso Regression – Machine Learning for Public Policy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-45c9daaf6acd34b0420988892e8b8644.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-73ee73b83b1a433826722856a32939c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets/ML4PP.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Machine Learning for Public Policy</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-introduction" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Introduction</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-introduction">    
        <li>
    <a class="dropdown-item" href="./introduction.html">
 <span class="dropdown-text">Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./r-intro.html">
 <span class="dropdown-text">An Introduction to R Programming</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./python-intro.html">
 <span class="dropdown-text">An introduction to Python programming</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-content" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Content</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-content">    
        <li>
    <a class="dropdown-item" href="./predictionpolicy.html">
 <span class="dropdown-text">Prediction Policy Problems: Linear Models and Lasso Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./classification.html">
 <span class="dropdown-text">Classification with Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./treebasedmodels.html">
 <span class="dropdown-text">Tree-based models for classification problems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./fairml.html">
 <span class="dropdown-text">Algorithmic Fairness</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./neuralNets.html">
 <span class="dropdown-text">An Introduction to Neural Networks</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./policyChallenge.html"> 
<span class="menu-text">Collaborative Policy Challenge</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/michelleg06/Machine-Learning-for-Public-Policy" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introducing-the-prediction-policy-framework" id="toc-introducing-the-prediction-policy-framework" class="nav-link active" data-scroll-target="#introducing-the-prediction-policy-framework">Introducing the Prediction Policy Framework</a>
  <ul class="collapse">
  <li><a href="#predicting-social-assistance-beneficiaries" id="toc-predicting-social-assistance-beneficiaries" class="nav-link" data-scroll-target="#predicting-social-assistance-beneficiaries">Predicting social assistance beneficiaries</a></li>
  </ul></li>
  <li><a href="#r-practical" id="toc-r-practical" class="nav-link" data-scroll-target="#r-practical">R Practical</a>
  <ul class="collapse">
  <li><a href="#preliminaries-working-directory-libraries-data-upload" id="toc-preliminaries-working-directory-libraries-data-upload" class="nav-link" data-scroll-target="#preliminaries-working-directory-libraries-data-upload">1. Preliminaries: working directory, libraries, data upload</a></li>
  <li><a href="#get-to-know-your-data-visualisation-and-pre-processing" id="toc-get-to-know-your-data-visualisation-and-pre-processing" class="nav-link" data-scroll-target="#get-to-know-your-data-visualisation-and-pre-processing">2. Get to know your data: visualisation and pre-processing</a></li>
  <li><a href="#model-fit-data-partition-and-performance-evaluation-parameters" id="toc-model-fit-data-partition-and-performance-evaluation-parameters" class="nav-link" data-scroll-target="#model-fit-data-partition-and-performance-evaluation-parameters">3. Model fit: data partition and performance evaluation parameters</a></li>
  <li><a href="#feature-selection-with-lasso-linear-regression" id="toc-feature-selection-with-lasso-linear-regression" class="nav-link" data-scroll-target="#feature-selection-with-lasso-linear-regression">4. Feature selection with Lasso linear regression</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#practice-at-home" id="toc-practice-at-home" class="nav-link" data-scroll-target="#practice-at-home">Practice at home</a></li>
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings">Readings</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prediction Policy Problems: Linear Models and Lasso Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>This section will cover:</strong></p>
<ul>
<li>Prediction Policy problems</li>
<li>Inference vs.&nbsp;prediction for policy analysis</li>
<li>Assessing accuracy: bias-variance tradeoff</li>
<li>Training error vs.&nbsp;test error</li>
<li>Feature selection: brief introduction to Lasso</li>
</ul>
<p><br></p>
<section id="introducing-the-prediction-policy-framework" class="level2">
<h2 class="anchored" data-anchor-id="introducing-the-prediction-policy-framework">Introducing the Prediction Policy Framework</h2>
<p>In the video-lecture below you’ll be given a brief introduction to the prediction policy framework, and a primer on machine learning. Please take a moment to watch the 20 minute video.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/sFbKe4O0tEQ" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Are you still wondering what the difference is between Machine Learning and Econometrics? Take a few minutes to watch the video below.</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/gx_MBxMu0m4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>After watching the videos, we have a practical exercise.</p>
<section id="predicting-social-assistance-beneficiaries" class="level3">
<h3 class="anchored" data-anchor-id="predicting-social-assistance-beneficiaries">Predicting social assistance beneficiaries</h3>
<p>A key problem in the design of Social Policies is the identification of people in need of social assistance. Social policies usually work with tight budgets and limited fiscal space. To allocate resources efficiently, benefits need to be targeted to those who need them most. Yet, identifying needs isn’t easy and misclassifications can have severe and irreversible effects on people in need.</p>
<p>Think of a social protection programme that allocates food vouchers to families with children at risk of malnutrition, or a programme that establishes needs-based school grants. What happens when these limited and finite resources are given to people that could do without, and those who need them most are excluded from them?</p>
<p>In this block we’ll work with real-world data from the country of Malawi to predict cash-transfer programme beneficiaries: People who live in poverty and need government assistance to make ends meet. The data comes from McBride and Nichol’s (2018) paper <a href="https://elibrary.worldbank.org/doi/abs/10.1093/wber/lhw056">Retooling poverty targeting using out-of-sample validation and machine learning</a>.</p>
<p><strong>Discussion Points</strong></p>
<p>The points below are meant to help you think critically about why we’re about to embark on a machine learning - targeting exercise. <br></p>
<ul>
<li>
Why is this a prediction policy problem? What would be a causal inference problem in this setting? Is it a regression or a classification problem?
</li>
<li>
<p>Which variables and characteristics that we include in the prediction model can make a big difference?</p>
<ul>
<li>
Programmatically and conceptually, which type of characteristics do we want to consider for the prediction model?
</li>
<li>
Technically, how do we select which variables to include in a prediction model? How is this different from a causal inference problem?
</li>
</ul>
</li>
<li>
What are the practical implications of the bias-variance tradeoff in this application?
</li>
<li>
What are potential risks of such a data driven targeting approach?
</li>
</ul>
<p><br></p>
<p><strong>If you’d like to learn more about Social Protection Policies, take a look at this video Alex has made for us with a brilliant summary of the field</strong></p>
<p>(Yes, more videos!)</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/Pn9DntDejKU" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
</section>
<section id="r-practical" class="level2">
<h2 class="anchored" data-anchor-id="r-practical">R Practical</h2>
<p>You can download the dataset by clicking on the button below.</p>
<p><a class="btn btn-primary" download="" href="data/malawi.csv"> Download Malawi.csv </a></p>
<p><br></p>
<p>The script below is a step by step on how to go about coding a predictive model using a <em>linear regression</em>. Despite its simplicity and transparency, i.e.&nbsp;the ease with which we can interpret its results, a linear model is not without challenges in machine learning.</p>
<section id="preliminaries-working-directory-libraries-data-upload" class="level3">
<h3 class="anchored" data-anchor-id="preliminaries-working-directory-libraries-data-upload">1. Preliminaries: working directory, libraries, data upload</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># this line cleans your Global Environment.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/lucas/Documents/UNU-CDO/courses/ml4p/ml4p-website-v2"</span>) <span class="co"># set your working directory</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Libraries</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># If this is your first time using R, you need to install the libraries before loading them. </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># To do that, you can uncomment the line that starts with install.packages(...) by removing the # symbol.    </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("dplyr", "tidyverse", "caret", "corrplot", "Hmisc", "modelsummary", "plyr", "gt", "stargazer", "elasticnet", "sandwich")</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co"># core package for dataframe manipulation. Usually installed and loaded with the tidyverse, but sometimes needs to be loaded in conjunction to avoid warnings.</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># a large collection of packages for data manipulation and visualisation.  </span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret) <span class="co"># a package with key functions that streamline the process for predictive modelling </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot) <span class="co"># a package to plot correlation matrices</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="co"># a package for general-purpose data analysis </span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary) <span class="co"># a package to describe model outputs</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr) <span class="co"># a package to describe dataframes</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr) <span class="co"># a package for data wrangling</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt) <span class="co"># a package to edit modelsummary (and other) tables</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer) <span class="co"># a package to visualise model output</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>data_malawi <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/malawi.csv"</span>) <span class="co"># the file is directly read from the working directory/folder previously set</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="get-to-know-your-data-visualisation-and-pre-processing" class="level3">
<h3 class="anchored" data-anchor-id="get-to-know-your-data-visualisation-and-pre-processing">2. Get to know your data: visualisation and pre-processing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(data_malawi) <span class="co"># describes the dataset in a nice format </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">data_malawi</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">11280</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">36</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">region</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">eatype</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">lnexp_pc_month</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.360000e+00</td>
<td style="text-align: right;">6.800000e-01</td>
<td style="text-align: right;">4.7800e+00</td>
<td style="text-align: right;">6.890000e+00</td>
<td style="text-align: right;">7.310000e+00</td>
<td style="text-align: right;">7.760000e+00</td>
<td style="text-align: right;">1.106000e+01</td>
<td style="text-align: left;">▁▇▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">hhsize</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.550000e+00</td>
<td style="text-align: right;">2.340000e+00</td>
<td style="text-align: right;">1.0000e+00</td>
<td style="text-align: right;">3.000000e+00</td>
<td style="text-align: right;">4.000000e+00</td>
<td style="text-align: right;">6.000000e+00</td>
<td style="text-align: right;">2.700000e+01</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hhsize2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.613000e+01</td>
<td style="text-align: right;">2.799000e+01</td>
<td style="text-align: right;">1.0000e+00</td>
<td style="text-align: right;">9.000000e+00</td>
<td style="text-align: right;">1.600000e+01</td>
<td style="text-align: right;">3.600000e+01</td>
<td style="text-align: right;">7.290000e+02</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">agehead</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.246000e+01</td>
<td style="text-align: right;">1.636000e+01</td>
<td style="text-align: right;">1.0000e+01</td>
<td style="text-align: right;">2.900000e+01</td>
<td style="text-align: right;">3.900000e+01</td>
<td style="text-align: right;">5.400000e+01</td>
<td style="text-align: right;">1.040000e+02</td>
<td style="text-align: left;">▅▇▅▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">agehead2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.070610e+03</td>
<td style="text-align: right;">1.618600e+03</td>
<td style="text-align: right;">1.0000e+02</td>
<td style="text-align: right;">8.410000e+02</td>
<td style="text-align: right;">1.521000e+03</td>
<td style="text-align: right;">2.916000e+03</td>
<td style="text-align: right;">1.081600e+04</td>
<td style="text-align: left;">▇▃▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">north</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.500000e-01</td>
<td style="text-align: right;">3.600000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">central</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.800000e-01</td>
<td style="text-align: right;">4.900000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">rural</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8.700000e-01</td>
<td style="text-align: right;">3.300000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▁▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nevermarried</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.000000e-02</td>
<td style="text-align: right;">1.700000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">sharenoedu</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.700000e-01</td>
<td style="text-align: right;">2.600000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">2.500000e-01</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">shareread</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.100000e-01</td>
<td style="text-align: right;">3.800000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">3.300000e-01</td>
<td style="text-align: right;">6.700000e-01</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▅▁▅▂▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">nrooms</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.500000e+00</td>
<td style="text-align: right;">1.300000e+00</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">2.000000e+00</td>
<td style="text-align: right;">2.000000e+00</td>
<td style="text-align: right;">3.000000e+00</td>
<td style="text-align: right;">1.600000e+01</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">floor_cement</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.000000e-01</td>
<td style="text-align: right;">4.000000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">electricity</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.000000e-02</td>
<td style="text-align: right;">2.300000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flushtoilet</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.000000e-02</td>
<td style="text-align: right;">1.700000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">soap</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.400000e-01</td>
<td style="text-align: right;">3.400000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bed</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.200000e-01</td>
<td style="text-align: right;">4.700000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">bike</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.600000e-01</td>
<td style="text-align: right;">4.800000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">musicplayer</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.600000e-01</td>
<td style="text-align: right;">3.700000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">coffeetable</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.200000e-01</td>
<td style="text-align: right;">3.200000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">iron</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.100000e-01</td>
<td style="text-align: right;">4.000000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">dimbagarden</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.200000e-01</td>
<td style="text-align: right;">4.700000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">goats</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.100000e-01</td>
<td style="text-align: right;">4.100000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">dependratio</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.120000e+00</td>
<td style="text-align: right;">9.500000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">5.000000e-01</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.500000e+00</td>
<td style="text-align: right;">9.000000e+00</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hfem</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.300000e-01</td>
<td style="text-align: right;">4.200000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">grassroof</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.400000e-01</td>
<td style="text-align: right;">4.400000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▃▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mortarpestle</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.000000e-01</td>
<td style="text-align: right;">5.000000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">table</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.600000e-01</td>
<td style="text-align: right;">4.800000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">clock</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.000000e-01</td>
<td style="text-align: right;">4.000000e-01</td>
<td style="text-align: right;">0.0000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">ea</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.606000e+01</td>
<td style="text-align: right;">1.885500e+02</td>
<td style="text-align: right;">1.0000e+00</td>
<td style="text-align: right;">8.000000e+00</td>
<td style="text-align: right;">1.900000e+01</td>
<td style="text-align: right;">4.525000e+01</td>
<td style="text-align: right;">9.010000e+02</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.372322e+07</td>
<td style="text-align: right;">7.241514e+06</td>
<td style="text-align: right;">1.0101e+07</td>
<td style="text-align: right;">2.040204e+07</td>
<td style="text-align: right;">2.090352e+07</td>
<td style="text-align: right;">3.053301e+07</td>
<td style="text-align: right;">3.120209e+07</td>
<td style="text-align: left;">▂▁▆▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">hhwght</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.387900e+02</td>
<td style="text-align: right;">7.001000e+01</td>
<td style="text-align: right;">7.9000e+01</td>
<td style="text-align: right;">2.076000e+02</td>
<td style="text-align: right;">2.471000e+02</td>
<td style="text-align: right;">2.913000e+02</td>
<td style="text-align: right;">3.587000e+02</td>
<td style="text-align: left;">▂▁▇▇▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">psu</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.372322e+07</td>
<td style="text-align: right;">7.241514e+06</td>
<td style="text-align: right;">1.0101e+07</td>
<td style="text-align: right;">2.040204e+07</td>
<td style="text-align: right;">2.090352e+07</td>
<td style="text-align: right;">3.053301e+07</td>
<td style="text-align: right;">3.120209e+07</td>
<td style="text-align: left;">▂▁▆▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">strataid</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.560000e+01</td>
<td style="text-align: right;">8.090000e+00</td>
<td style="text-align: right;">1.0000e+00</td>
<td style="text-align: right;">9.000000e+00</td>
<td style="text-align: right;">1.500000e+01</td>
<td style="text-align: right;">2.200000e+01</td>
<td style="text-align: right;">3.000000e+01</td>
<td style="text-align: left;">▅▇▇▆▅</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lnzline</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.550000e+00</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">7.5500e+00</td>
<td style="text-align: right;">7.550000e+00</td>
<td style="text-align: right;">7.550000e+00</td>
<td style="text-align: right;">7.550000e+00</td>
<td style="text-align: right;">7.550000e+00</td>
<td style="text-align: left;">▁▁▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">case_id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.372322e+10</td>
<td style="text-align: right;">7.241514e+09</td>
<td style="text-align: right;">1.0101e+10</td>
<td style="text-align: right;">2.040204e+10</td>
<td style="text-align: right;">2.090352e+10</td>
<td style="text-align: right;">3.053301e+10</td>
<td style="text-align: right;">3.120209e+10</td>
<td style="text-align: left;">▂▁▆▁▇</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<ul>
<li><p>The dataset contains 38 variables and 11,280 observations.</p></li>
<li><p>Not all of these variables are relevant for our prediction model.</p></li>
<li><p>To find the labels and description of the variables, you can refer to the <a href="https://academic.oup.com/wber/article-abstract/32/3/531/2447896">paper</a>. <br></p></li>
</ul>
<p>[hhsize, hhsize2, age_head, age_head2, regions, rural, never married, share_of_adults_without_education, share_of_adults_who_can_read, number of rooms, cement floor, electricity, flush toilet, soap, bed, bike, music player, coffee table, iron, garden, goats]</p>
<ul>
<li><p>Luckily for us, we have no missing values (n_missing in summary output)!</p>
<ol type="A">
<li><p>Many machine learning models cannot be trained when missing values are present (some exceptions exist).</p></li>
<li><p>Dealing with missingness is a non-trivial task:</p></li>
</ol></li>
</ul>
<p>First and foremost, we should assess whether there is a pattern to missingness and if so, what that means to what we can learn from our (sub)population. If there is no discernible pattern, we can proceed to delete the missing values or impute them. A more detailed explanation and course of action can be found <a href="https://stefvanbuuren.name/fimd/sec-MCAR.html">here</a>.</p>
<section id="feature-selection-subsetting-the-dataset" class="level4">
<h4 class="anchored" data-anchor-id="feature-selection-subsetting-the-dataset">Feature selection: subsetting the dataset</h4>
<p>As part of our data pre-processing we will subset the dataframe, such that only relevant variables are left. * Relevant: variables/features about a household that could help us determine whether they are in poverty. That way, we save some memory space; but also, we can call the full set of variables in a dataframe in one go!</p>
<pre><code>variables to delete (not included in the identified set above):
[ea, EA, hhwght, psu, strataid, lnzline, case_id, eatype] </code></pre>
<p><br></p>
<p><strong>N/B</strong>: Feature selection is a <em>critical process</em> (and we normally don’t have a paper to guide us through it): from a practical point of view, a model with less predictors may be easier to interpret. Also, some models may be negatively affected by non-informative predictors. This process is similar to traditional econometric modelling, but we should not conflate predictive and explanatory modelling. Importantly, please note that we are not interested in knowing why something happens, but rather in what is likely to happen given some known data. Hence:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># object:vector that contains the names of the variables that we want to get rid of</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ea"</span>, <span class="st">"EA"</span>, <span class="st">"psu"</span>,<span class="st">"hhwght"</span>, <span class="st">"strataid"</span>, <span class="st">"lnzline"</span>, <span class="st">"case_id"</span>,<span class="st">"eatype"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># subset of the data_malawi object:datframe</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>data_malawi <span class="ot">&lt;-</span> data_malawi[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">colnames</span>(data_malawi) <span class="sc">%in%</span> cols)] <span class="co"># the minus sign indicates deletion of cols</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A few notes for you:</p>
<ul>
<li><p>a dataframe follows the form data[rows,colums]</p></li>
<li><p>colnames() is a function that identifies the column names of an object of class dataframe</p></li>
<li><p>which() is an R base function that gives you the position of some value</p></li>
<li><p>a minus sign will delete either the identified position in the row or the column space</p></li>
</ul>
</section>
<section id="data-visualisation" class="level4">
<h4 class="anchored" data-anchor-id="data-visualisation">Data visualisation</h4>
<p>A quick and effective way to take a first glance at our data is to plot histograms of relevant (numeric) features.</p>
<p>Recall (from the skim() dataframe summary output) that only two variables are non-numeric. However, we need to make a distinction between class factor and class numeric/numeric.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># identify categorical variables to transform from class numeric to factor</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># using a for-loop: print the number of unique values by variable</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(data_malawi)) { <span class="co"># iterate over the length of columns in the data_malawi df</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># store the number of unique values in column.i </span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(data_malawi[[i]]))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># print the name of column.i</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">colnames</span>(data_malawi[i]))</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># print the number of unique values in column.i</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(x)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "lnexp_pc_month"
[1] 11266
[1] "hhsize"
[1] 19
[1] "hhsize2"
[1] 19
[1] "agehead"
[1] 88
[1] "agehead2"
[1] 88
[1] "north"
[1] 2
[1] "central"
[1] 2
[1] "rural"
[1] 2
[1] "nevermarried"
[1] 2
[1] "sharenoedu"
[1] 47
[1] "shareread"
[1] 28
[1] "nrooms"
[1] 16
[1] "floor_cement"
[1] 2
[1] "electricity"
[1] 2
[1] "flushtoilet"
[1] 2
[1] "soap"
[1] 2
[1] "bed"
[1] 2
[1] "bike"
[1] 2
[1] "musicplayer"
[1] 2
[1] "coffeetable"
[1] 2
[1] "iron"
[1] 2
[1] "dimbagarden"
[1] 2
[1] "goats"
[1] 2
[1] "dependratio"
[1] 62
[1] "hfem"
[1] 2
[1] "grassroof"
[1] 2
[1] "mortarpestle"
[1] 2
[1] "table"
[1] 2
[1] "clock"
[1] 2
[1] "region"
[1] 3</code></pre>
</div>
</div>
<p>If you want to optimise your code, using for loops is not ideal. In R, there exists a family of functions called Apply whose purpose is to apply some function to all the elements in an object. For the time being, iterating over 38 columns is fast enough and we don’t need to think about optimising our code. We’ll also see an example later on on how to use one of the functions from the apply family. You can also refer to this blog (https://www.r-bloggers.com/2021/05/apply-family-in-r-apply-lapply-sapply-mapply-and-tapply/) if you want to learn more about it.</p>
<p>Notice that we have a few variables with 2 unique values and one variable with 3 unique values. We should transform these into factor() class. Recall from the introduction tab that in object-oriented programming correctly identifying the variable type (vector class) is crucial for data manipulation and arithmetic operations. We can do this one by one, or in one shot. I’ll give an example of both:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># == One by one == # </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># transform a variable in df to factor, and pass it on to the df to keep the change</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># first, sneak peak at the first 5 observations (rows) of the vector</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_malawi<span class="sc">$</span>north) <span class="co"># returns 1 = North </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 1 1 1 1 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>data_malawi<span class="sc">$</span>north <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_malawi<span class="sc">$</span>north, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"NotNorth"</span>, <span class="st">"North"</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data_malawi<span class="sc">$</span>north) <span class="co"># returns 2?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "NotNorth","North": 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_malawi<span class="sc">$</span>north) <span class="co"># returns north (which was = 1 before), hooray!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] North North North North North North
Levels: NotNorth North</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R stores factors as 1...n; but the label remains the initial numeric value assigned (1 for true, 0 false)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We have also explicityly told 0 is NotNorth and 1 is North (by the order that follows the line of code)</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># transform all binary/categorical data into factor class</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>min_count <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="co"># vector: 3 categories is our max number of categories found</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># == Apply family: function apply and lapply==#</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># apply a length(unique(x)) function to all the columns (rows = 1, columns = 2) of the data_malawi dataframe, then</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># store boolean (true/false) if the number of unique values is lower or equal to the min_count vector</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>n_distinct2 <span class="ot">&lt;-</span> <span class="fu">apply</span>(data_malawi, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">length</span>(<span class="fu">unique</span>(x))) <span class="sc">&lt;=</span> min_count</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># print(n_distinct2) # prints boolean indicator object (so you know what object you have created)</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co"># select the identified categorical variables and transform them into factors</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>data_malawi[n_distinct2] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(data_malawi[n_distinct2], factor) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Visualise your data: histograms, bar plots, tables</strong></p>
<p>Let’s start with histograms of numeric (continuous) variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># == HISTOGRAMS == #</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Select all variables in the dataframe which are numeric, and can therefore be plotted as a histogram.</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>malawi_continuous <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data_malawi <span class="sc">%&gt;%</span> <span class="fu">select_if</span>(<span class="sc">~</span><span class="fu">is.numeric</span>(.))) </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># a quick glance at the summary statistics of our continuous variables</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">datasummary_skim</span>(malawi_continuous) <span class="co"># from modelsummary pkg, output as plot in Plot Viewer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script>

      function styleCell_jzf8bl1ppj0mtrasnwjr(i, j, css_id) {
          var table = document.getElementById("tinytable_jzf8bl1ppj0mtrasnwjr");
          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_jzf8bl1ppj0mtrasnwjr');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_jzf8bl1ppj0mtrasnwjr(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_jzf8bl1ppj0mtrasnwjr");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: 9, j: 2 }, { i: 9, j: 3 }, { i: 9, j: 7 }, { i: 9, j: 1 }, { i: 9, j: 5 }, { i: 9, j: 6 }, { i: 9, j: 0 }, { i: 9, j: 4 }, { i: 9, j: 8 },  ], css_id: 'tinytable_css_k51984tm2apq8eyfwnbw',}, 
          { positions: [ { i: 0, j: 0 }, { i: 0, j: 4 }, { i: 0, j: 8 }, { i: 0, j: 2 }, { i: 0, j: 3 }, { i: 0, j: 7 }, { i: 0, j: 1 }, { i: 0, j: 5 }, { i: 0, j: 6 },  ], css_id: 'tinytable_css_cry8pvfl27yw9tx70r3v',}, 
          { positions: [ { i: 2, j: 2 }, { i: 6, j: 0 }, { i: 3, j: 0 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 6, j: 1 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 2, j: 3 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 5, j: 3 }, { i: 3, j: 2 }, { i: 1, j: 1 }, { i: 5, j: 2 }, { i: 6, j: 2 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 2, j: 4 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 5, j: 4 }, { i: 3, j: 3 }, { i: 1, j: 2 }, { i: 8, j: 4 }, { i: 6, j: 3 }, { i: 4, j: 2 }, { i: 8, j: 3 }, { i: 2, j: 5 }, { i: 7, j: 2 }, { i: 8, j: 2 }, { i: 5, j: 5 }, { i: 3, j: 4 }, { i: 1, j: 3 }, { i: 8, j: 5 }, { i: 6, j: 4 }, { i: 4, j: 3 }, { i: 1, j: 6 }, { i: 2, j: 6 }, { i: 7, j: 3 }, { i: 1, j: 5 }, { i: 5, j: 6 }, { i: 3, j: 5 }, { i: 1, j: 4 }, { i: 8, j: 6 }, { i: 6, j: 5 }, { i: 4, j: 4 }, { i: 1, j: 7 }, { i: 2, j: 7 }, { i: 7, j: 4 }, { i: 4, j: 7 }, { i: 5, j: 7 }, { i: 3, j: 6 }, { i: 4, j: 6 }, { i: 8, j: 7 }, { i: 6, j: 6 }, { i: 4, j: 5 }, { i: 1, j: 8 }, { i: 2, j: 8 }, { i: 7, j: 5 }, { i: 4, j: 8 }, { i: 5, j: 8 }, { i: 3, j: 7 }, { i: 7, j: 8 }, { i: 8, j: 8 }, { i: 6, j: 7 }, { i: 7, j: 7 }, { i: 6, j: 8 }, { i: 3, j: 8 }, { i: 7, j: 6 },  ], css_id: 'tinytable_css_2d5bd5fslp9nnlkx9n6j',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_jzf8bl1ppj0mtrasnwjr(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <style>
      /* tinytable css entries after */
      .table td.tinytable_css_k51984tm2apq8eyfwnbw, .table th.tinytable_css_k51984tm2apq8eyfwnbw { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_cry8pvfl27yw9tx70r3v, .table th.tinytable_css_cry8pvfl27yw9tx70r3v { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_2d5bd5fslp9nnlkx9n6j, .table th.tinytable_css_2d5bd5fslp9nnlkx9n6j { text-align: left; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_jzf8bl1ppj0mtrasnwjr" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        
              <tr>
                <th scope="col"> </th>
                <th scope="col">Unique</th>
                <th scope="col">Missing Pct.</th>
                <th scope="col">Mean</th>
                <th scope="col">SD</th>
                <th scope="col">Min</th>
                <th scope="col">Median</th>
                <th scope="col">Max</th>
                <th scope="col">Histogram</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td>lnexp_pc_month</td>
                  <td>11266</td>
                  <td>0</td>
                  <td>7.4</td>
                  <td>0.7</td>
                  <td>4.8</td>
                  <td>7.3</td>
                  <td>11.1</td>
                  <td><img src="./tinytable_assets/id7om8tlqt9ty5xg2div1n.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>hhsize</td>
                  <td>19</td>
                  <td>0</td>
                  <td>4.5</td>
                  <td>2.3</td>
                  <td>1.0</td>
                  <td>4.0</td>
                  <td>27.0</td>
                  <td><img src="./tinytable_assets/id6nauzrr5tsaj8xmkgvbc.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>hhsize2</td>
                  <td>19</td>
                  <td>0</td>
                  <td>26.1</td>
                  <td>28.0</td>
                  <td>1.0</td>
                  <td>16.0</td>
                  <td>729.0</td>
                  <td><img src="./tinytable_assets/idyi8d4o8jljijyn4kdssr.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>agehead</td>
                  <td>88</td>
                  <td>0</td>
                  <td>42.5</td>
                  <td>16.4</td>
                  <td>10.0</td>
                  <td>39.0</td>
                  <td>104.0</td>
                  <td><img src="./tinytable_assets/idbau69ij8bxmhmlvsce65.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>agehead2</td>
                  <td>88</td>
                  <td>0</td>
                  <td>2070.6</td>
                  <td>1618.6</td>
                  <td>100.0</td>
                  <td>1521.0</td>
                  <td>10816.0</td>
                  <td><img src="./tinytable_assets/idoiu59g5q771zxkqypdk8.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>sharenoedu</td>
                  <td>47</td>
                  <td>0</td>
                  <td>0.2</td>
                  <td>0.3</td>
                  <td>0.0</td>
                  <td>0.0</td>
                  <td>1.0</td>
                  <td><img src="./tinytable_assets/id45skftozx5vwx3i3p481.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>shareread</td>
                  <td>28</td>
                  <td>0</td>
                  <td>0.6</td>
                  <td>0.4</td>
                  <td>0.0</td>
                  <td>0.7</td>
                  <td>1.0</td>
                  <td><img src="./tinytable_assets/idgrlzj4sivapby5mdc0x8.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>nrooms</td>
                  <td>16</td>
                  <td>0</td>
                  <td>2.5</td>
                  <td>1.3</td>
                  <td>0.0</td>
                  <td>2.0</td>
                  <td>16.0</td>
                  <td><img src="./tinytable_assets/idvgk58g70y5yt63y3aerc.png" style="height: 1em;"></td>
                </tr>
                <tr>
                  <td>dependratio</td>
                  <td>62</td>
                  <td>0</td>
                  <td>1.1</td>
                  <td>0.9</td>
                  <td>0.0</td>
                  <td>1.0</td>
                  <td>9.0</td>
                  <td><img src="./tinytable_assets/idiqexcv7kvcvuxm9j4bnq.png" style="height: 1em;"></td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hmisc package, quick and painless hist.data.frame() function</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># but first, make sure to adjust the number of rows and columns to be displayed on your Plot Viewer</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>)) <span class="co"># 3 rows * 3 columns (9 variables)</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist.data.frame</span>(malawi_continuous)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="predictionpolicy_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, let’s plot bar graphs and write tables of factor (categorical) variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># == BAR GRAPHS == #</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>malawi_factor <span class="ot">&lt;-</span> data_malawi <span class="sc">%&gt;%</span> <span class="fu">select_if</span>(<span class="sc">~</span><span class="fu">is.factor</span>(.)) <span class="co"># subset of the data with all factor variables</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">7</span>)) <span class="co"># 7 rows, 3 columns (21 variables = length of df)</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(malawi_factor)) { <span class="co"># Loop over all the columns in the factor df subset</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># store data in column.i as x</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> malawi_factor[,i]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># store name of column.i as x_name</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    x_name <span class="ot">&lt;-</span> <span class="fu">colnames</span>(malawi_factor[i])</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Plot bar graph of x using Rbase plotting tools</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">barplot</span>(<span class="fu">table</span>(x),</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">main =</span> <span class="fu">paste</span>(x_name)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="predictionpolicy_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># == TABLES == #</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># We can also show tables of all factor variables (to get precise frequencies not displayed in bar plots)</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">llply</span>(<span class="at">.data=</span>malawi_factor, <span class="at">.fun=</span>table) <span class="co"># create tables of all the variables in dataframe using the plyr package</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$north

NotNorth    North 
    9600     1680 

$central

   0    1 
6960 4320 

$rural

   0    1 
1440 9840 

$nevermarried

    0     1 
10930   350 

$floor_cement

   0    1 
9036 2244 

$electricity

    0     1 
10620   660 

$flushtoilet

    0     1 
10962   318 

$soap

   0    1 
9740 1540 

$bed

   0    1 
7653 3627 

$bike

   0    1 
7194 4086 

$musicplayer

   0    1 
9426 1854 

$coffeetable

   0    1 
9956 1324 

$iron

   0    1 
8962 2318 

$dimbagarden

   0    1 
7658 3622 

$goats

   0    1 
8856 2424 

$hfem

   0    1 
8697 2583 

$grassroof

   0    1 
2953 8327 

$mortarpestle

   0    1 
5635 5645 

$table

   0    1 
7249 4031 

$clock

   0    1 
9039 2241 

$region

Centre  North  South 
  4320   1680   5280 </code></pre>
</div>
</div>
<p><br></p>
<p>What have we learned from the data visualisation?</p>
<ol type="a">
<li><p>Nothing worrying about the data itself. McBride and Nichols did a good job of pre-processing the data for us. No pesky missing values, or unknown categories.</p></li>
<li><p>From the bar plots, we can see that for the most part, people tend not to own assets. Worryingly, there is a lack of soap, flush toilets and electricity, all of which are crucial for human capital (health and education).</p></li>
<li><p>From the histograms, we can see log per capita expenditure is normally distributed, but if we remove the log, it’s incredibly skewed. Poverty is endemic. Households tend not to have too many educated individuals, and their size is non-trivially large (with less rooms than people need).</p></li>
</ol>
</section>
<section id="relationships-between-features" class="level4">
<h4 class="anchored" data-anchor-id="relationships-between-features">Relationships between features</h4>
<p>To finalise our exploration of the dataset, we should define:</p>
<ul>
<li><p>the target variable (a.k.a. outcome of interest)</p></li>
<li><p>correlational insights</p></li>
</ul>
<p>Let’s visualise two distinct correlation matrices; for our numeric dataframe, which includes our target variable, we will plot a Pearson r correlation matrix. For our factor dataframe, to which we will add our continuous target, we will plot a Spearman rho correlation matrix. Both types of correlation coefficients are interpreted the same (0 = no correlation, 1 perfect positive correlation, -1 perfect negative correlation).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># = = PEARSON CORRELATION MATRIX = = #</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(malawi_continuous) <span class="co"># create a correlation matrix of the continuous dataset, cor() uses Pearson's correlation coefficient as default. This means we can only take the correlation between continuous variables</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(M, <span class="at">method=</span><span class="st">"circle"</span>, <span class="at">addCoef.col =</span><span class="st">"black"</span>, <span class="at">number.cex =</span> <span class="fl">0.8</span>) <span class="co"># visualise it in a nice way</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="predictionpolicy_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can already tell that the size of the household and dependent ratio are highly negatively correlated to our target variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># = = SPEARMAN CORRELATION MATRIX = = #</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>malawi_factorC <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(malawi_factor,as.numeric)) <span class="co"># coerce dataframe to numeric, as the cor() command only takes in numeric types</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>malawi_factorC<span class="sc">$</span>lnexp_pc_month <span class="ot">&lt;-</span> malawi_continuous<span class="sc">$</span>lnexp_pc_month <span class="co"># include target variable in the dataframe</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(malawi_factorC, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(M2, <span class="at">method=</span><span class="st">"circle"</span>, <span class="at">addCoef.col =</span><span class="st">"black"</span>, <span class="at">number.cex =</span> <span class="fl">0.3</span>) <span class="co"># visualise it in a nice way</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="predictionpolicy_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ownership of some assets stands out: soap, a cement floor, electricity, a bed… ownership of these (and a couple of other) assets is positively correlated to per capita expenditure. Living in a rural area, on the other hand, is negtively correlated to our target variable.</p>
<p>We can also spot some correlation coefficients that equal zero. In some situations, the data generating mechanism can create predictors that only have a single unique value (i.e.&nbsp;a “zero-variance predictor”). For many ML models (excluding tree-based models), this may cause the model to crash or the fit to be unstable. Here, the only <span class="math inline">\(0\)</span> we’ve spotted is not in relation to our target variable.</p>
<p>But we do observe some near-zero-variance predictors. Besides uninformative, these can also create unstable model fits. There’s a few strategies to deal with these; the quickest solution is to remove them. A second option, which is especially interesting in scenarios with a large number of predictors/variables, is to work with penalised models. We’ll discuss this option below.</p>
</section>
</section>
<section id="model-fit-data-partition-and-performance-evaluation-parameters" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-data-partition-and-performance-evaluation-parameters">3. Model fit: data partition and performance evaluation parameters</h3>
<p>We now have a general idea of the structure of the data we are working with, and what we’re trying to predict: per capita expenditures, which we believe are a proxy for poverty prevalence. Measured by the log of per capita monthly expenditure in our dataset, the variable is named lnexp_pc_month.</p>
<p>The next step is create a simple linear model (OLS) to predict per capita expenditure using the variables in our dataset, and introduce the elements with which we will evaluate our model.</p>
<section id="data-partinioning" class="level4">
<h4 class="anchored" data-anchor-id="data-partinioning">Data Partinioning</h4>
<p>When we want to build predictive models for machine learning purposes, it is important to have (at least) two data sets. A training data set from which our model will learn, and a test data set containing the same features as our training data set; we use the second dataset to see how well our predictive model extrapolates to other samples (i.e.&nbsp;is it generalisable?). To split our main data set into two, we will work with an 80/20 split.</p>
<p>The 80/20 split has its origins in the Pareto Principle, which states that ‘in most cases, 80% of effects from from 20% of causes’. Though there are other test/train splitting options, this partitioning method is a good place to start, and indeed standard in the machine learning field.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, set a seed to guarantee replicability of the process</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co"># you can use any number you want, but to replicate the results in this tutorial you need to use this number</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We could split the data manually, but the caret package includes an useful function</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>train_idx <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(data_malawi<span class="sc">$</span>lnexp_pc_month, <span class="at">p =</span> .<span class="dv">8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>, <span class="at">times =</span> <span class="dv">1</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train_idx) <span class="co"># notice that observation 5 corresponds to resame indicator 7 and so on. We're shuffling and picking!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Resample1
[1,]         1
[2,]         2
[3,]         4
[4,]         5
[5,]         7
[6,]         8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>Train_df <span class="ot">&lt;-</span> data_malawi[ train_idx,]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>Test_df  <span class="ot">&lt;-</span> data_malawi[<span class="sc">-</span>train_idx,]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that we have created training and testing dataframes as an 80/20 split of the original dataset.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="prediction-with-linear-models" class="level4">
<h4 class="anchored" data-anchor-id="prediction-with-linear-models">Prediction with Linear Models</h4>
<p>We will start by fitting a predictive model using the training dataset; that is, our target variable <em>log of monthly per capita expenditures</em> or <em>lnexp_pc_month</em> will be a <span class="math inline">\(Y\)</span> dependent variable in a linear model <span class="math inline">\(Y_i = \alpha + x'\beta_i + \epsilon_i\)</span>, and the remaining features in the data frame correspond to the row vectors <span class="math inline">\(x'\beta\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lnexp_pc_month <span class="sc">~</span> .,Train_df) <span class="co"># the dot after the squiggle ~ asks the lm() function tu use all other variables in the dataframe as predictors to the dependent variable lnexp_pc_month</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1, <span class="at">type =</span> <span class="st">"text"</span>) <span class="co"># printed in the console as text</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                          lnexp_pc_month       
-----------------------------------------------
hhsize                       -0.292***         
                              (0.006)          
                                               
hhsize2                      0.012***          
                             (0.0005)          
                                               
agehead                        0.003           
                              (0.002)          
                                               
agehead2                    -0.00004**         
                             (0.00002)         
                                               
northNorth                   0.080***          
                              (0.014)          
                                               
central1                     0.252***          
                              (0.010)          
                                               
rural1                       -0.055***         
                              (0.017)          
                                               
nevermarried1                0.271***          
                              (0.028)          
                                               
sharenoedu                   -0.105***         
                              (0.020)          
                                               
shareread                    0.075***          
                              (0.015)          
                                               
nrooms                       0.039***          
                              (0.004)          
                                               
floor_cement1                0.102***          
                              (0.017)          
                                               
electricity1                 0.372***          
                              (0.027)          
                                               
flushtoilet1                 0.329***          
                              (0.033)          
                                               
soap1                        0.215***          
                              (0.014)          
                                               
bed1                         0.104***          
                              (0.013)          
                                               
bike1                        0.094***          
                              (0.011)          
                                               
musicplayer1                 0.111***          
                              (0.015)          
                                               
coffeetable1                 0.137***          
                              (0.019)          
                                               
iron1                        0.130***          
                              (0.014)          
                                               
dimbagarden1                 0.102***          
                              (0.010)          
                                               
goats1                       0.080***          
                              (0.012)          
                                               
dependratio                  -0.045***         
                              (0.006)          
                                               
hfem1                        -0.066***         
                              (0.012)          
                                               
grassroof1                   -0.096***         
                              (0.016)          
                                               
mortarpestle1                0.033***          
                              (0.010)          
                                               
table1                       0.051***          
                              (0.011)          
                                               
clock1                       0.058***          
                              (0.014)          
                                               
regionNorth                                    
                                               
                                               
regionSouth                                    
                                               
                                               
Constant                     7.978***          
                              (0.044)          
                                               
-----------------------------------------------
Observations                   9,024           
R2                             0.599           
Adjusted R2                    0.597           
Residual Std. Error      0.428 (df = 8995)     
F Statistic         479.041*** (df = 28; 8995) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can also estimate iid and robust standard errors, using the model output package modelsummary()</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>ms <span class="ot">&lt;-</span> <span class="fu">modelsummary</span>(model1,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">vcov =</span> <span class="fu">list</span>(<span class="st">"iid"</span>,<span class="st">"robust"</span>), <span class="co"># include iid and HC3 (robust) standard errors</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">statistic =</span> <span class="fu">c</span>(<span class="st">"p = {p.value}"</span>,<span class="st">"s.e. = {std.error}"</span>),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">stars =</span> <span class="cn">TRUE</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">output =</span> <span class="st">"gt"</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>             ) <span class="co"># plotted as an image / object in "gt" format</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>ms <span class="sc">%&gt;%</span> <span class="fu">tab_header</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">md</span>(<span class="st">"**Linear Models with iid and robust s.e.**"</span>),</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">md</span>(<span class="st">"Target: (log) per capita monthly expenditure"</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fwpwqhkfgg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#fwpwqhkfgg table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#fwpwqhkfgg thead, #fwpwqhkfgg tbody, #fwpwqhkfgg tfoot, #fwpwqhkfgg tr, #fwpwqhkfgg td, #fwpwqhkfgg th {
  border-style: none;
}

#fwpwqhkfgg p {
  margin: 0;
  padding: 0;
}

#fwpwqhkfgg .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#fwpwqhkfgg .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#fwpwqhkfgg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#fwpwqhkfgg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#fwpwqhkfgg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fwpwqhkfgg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fwpwqhkfgg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fwpwqhkfgg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#fwpwqhkfgg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#fwpwqhkfgg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#fwpwqhkfgg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#fwpwqhkfgg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#fwpwqhkfgg .gt_spanner_row {
  border-bottom-style: hidden;
}

#fwpwqhkfgg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#fwpwqhkfgg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#fwpwqhkfgg .gt_from_md > :first-child {
  margin-top: 0;
}

#fwpwqhkfgg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#fwpwqhkfgg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#fwpwqhkfgg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#fwpwqhkfgg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#fwpwqhkfgg .gt_row_group_first td {
  border-top-width: 2px;
}

#fwpwqhkfgg .gt_row_group_first th {
  border-top-width: 2px;
}

#fwpwqhkfgg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwpwqhkfgg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#fwpwqhkfgg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#fwpwqhkfgg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fwpwqhkfgg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwpwqhkfgg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#fwpwqhkfgg .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#fwpwqhkfgg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#fwpwqhkfgg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fwpwqhkfgg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fwpwqhkfgg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwpwqhkfgg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fwpwqhkfgg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwpwqhkfgg .gt_left {
  text-align: left;
}

#fwpwqhkfgg .gt_center {
  text-align: center;
}

#fwpwqhkfgg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#fwpwqhkfgg .gt_font_normal {
  font-weight: normal;
}

#fwpwqhkfgg .gt_font_bold {
  font-weight: bold;
}

#fwpwqhkfgg .gt_font_italic {
  font-style: italic;
}

#fwpwqhkfgg .gt_super {
  font-size: 65%;
}

#fwpwqhkfgg .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#fwpwqhkfgg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#fwpwqhkfgg .gt_indent_1 {
  text-indent: 5px;
}

#fwpwqhkfgg .gt_indent_2 {
  text-indent: 10px;
}

#fwpwqhkfgg .gt_indent_3 {
  text-indent: 15px;
}

#fwpwqhkfgg .gt_indent_4 {
  text-indent: 20px;
}

#fwpwqhkfgg .gt_indent_5 {
  text-indent: 25px;
}

#fwpwqhkfgg .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#fwpwqhkfgg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<th colspan="3" class="gt_heading gt_title gt_font_normal"><strong>Linear Models with iid and robust s.e.</strong></th>
</tr>
<tr class="gt_heading even">
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Target: (log) per capita monthly expenditure</th>
</tr>
<tr class="gt_col_headings header">
<th id="a-" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"></th>
<th id="a(1)" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">(1)</th>
<th id="a(2)" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">(2)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers=" ">(Intercept)</td>
<td class="gt_row gt_center" headers="(1)">7.978***</td>
<td class="gt_row gt_center" headers="(2)">7.978***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.044</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.069</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">hhsize</td>
<td class="gt_row gt_center" headers="(1)">-0.292***</td>
<td class="gt_row gt_center" headers="(2)">-0.292***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.006</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.029</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">hhsize2</td>
<td class="gt_row gt_center" headers="(1)">0.012***</td>
<td class="gt_row gt_center" headers="(2)">0.012***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.000</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.003</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">agehead</td>
<td class="gt_row gt_center" headers="(1)">0.003</td>
<td class="gt_row gt_center" headers="(2)">0.003</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = 0.108</td>
<td class="gt_row gt_center" headers="(2)">p = 0.137</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.002</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.002</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">agehead2</td>
<td class="gt_row gt_center" headers="(1)">-0.000*</td>
<td class="gt_row gt_center" headers="(2)">-0.000*</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = 0.015</td>
<td class="gt_row gt_center" headers="(2)">p = 0.032</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.000</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.000</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">northNorth</td>
<td class="gt_row gt_center" headers="(1)">0.080***</td>
<td class="gt_row gt_center" headers="(2)">0.080***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.014</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.015</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">central1</td>
<td class="gt_row gt_center" headers="(1)">0.252***</td>
<td class="gt_row gt_center" headers="(2)">0.252***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.010</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.010</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">rural1</td>
<td class="gt_row gt_center" headers="(1)">-0.055**</td>
<td class="gt_row gt_center" headers="(2)">-0.055**</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = 0.001</td>
<td class="gt_row gt_center" headers="(2)">p = 0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.017</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.017</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">nevermarried1</td>
<td class="gt_row gt_center" headers="(1)">0.271***</td>
<td class="gt_row gt_center" headers="(2)">0.271***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.028</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.037</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">sharenoedu</td>
<td class="gt_row gt_center" headers="(1)">-0.105***</td>
<td class="gt_row gt_center" headers="(2)">-0.105***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.020</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.021</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">shareread</td>
<td class="gt_row gt_center" headers="(1)">0.075***</td>
<td class="gt_row gt_center" headers="(2)">0.075***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.015</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.015</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">nrooms</td>
<td class="gt_row gt_center" headers="(1)">0.039***</td>
<td class="gt_row gt_center" headers="(2)">0.039***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.004</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.004</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">floor_cement1</td>
<td class="gt_row gt_center" headers="(1)">0.102***</td>
<td class="gt_row gt_center" headers="(2)">0.102***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.017</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.018</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">electricity1</td>
<td class="gt_row gt_center" headers="(1)">0.372***</td>
<td class="gt_row gt_center" headers="(2)">0.372***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.027</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.029</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">flushtoilet1</td>
<td class="gt_row gt_center" headers="(1)">0.329***</td>
<td class="gt_row gt_center" headers="(2)">0.329***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.033</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.042</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">soap1</td>
<td class="gt_row gt_center" headers="(1)">0.215***</td>
<td class="gt_row gt_center" headers="(2)">0.215***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.014</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.014</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">bed1</td>
<td class="gt_row gt_center" headers="(1)">0.104***</td>
<td class="gt_row gt_center" headers="(2)">0.104***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.013</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.013</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">bike1</td>
<td class="gt_row gt_center" headers="(1)">0.094***</td>
<td class="gt_row gt_center" headers="(2)">0.094***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.011</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.011</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">musicplayer1</td>
<td class="gt_row gt_center" headers="(1)">0.111***</td>
<td class="gt_row gt_center" headers="(2)">0.111***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.015</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.015</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">coffeetable1</td>
<td class="gt_row gt_center" headers="(1)">0.137***</td>
<td class="gt_row gt_center" headers="(2)">0.137***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.019</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.019</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">iron1</td>
<td class="gt_row gt_center" headers="(1)">0.130***</td>
<td class="gt_row gt_center" headers="(2)">0.130***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.014</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.014</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">dimbagarden1</td>
<td class="gt_row gt_center" headers="(1)">0.102***</td>
<td class="gt_row gt_center" headers="(2)">0.102***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.010</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.010</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">goats1</td>
<td class="gt_row gt_center" headers="(1)">0.080***</td>
<td class="gt_row gt_center" headers="(2)">0.080***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.012</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.012</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">dependratio</td>
<td class="gt_row gt_center" headers="(1)">-0.045***</td>
<td class="gt_row gt_center" headers="(2)">-0.045***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.006</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.009</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">hfem1</td>
<td class="gt_row gt_center" headers="(1)">-0.066***</td>
<td class="gt_row gt_center" headers="(2)">-0.066***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.012</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.013</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">grassroof1</td>
<td class="gt_row gt_center" headers="(1)">-0.096***</td>
<td class="gt_row gt_center" headers="(2)">-0.096***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.016</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.016</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">mortarpestle1</td>
<td class="gt_row gt_center" headers="(1)">0.033**</td>
<td class="gt_row gt_center" headers="(2)">0.033**</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = 0.001</td>
<td class="gt_row gt_center" headers="(2)">p = 0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.010</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.010</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">table1</td>
<td class="gt_row gt_center" headers="(1)">0.051***</td>
<td class="gt_row gt_center" headers="(2)">0.051***</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">s.e. = 0.011</td>
<td class="gt_row gt_center" headers="(2)">s.e. = 0.012</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">clock1</td>
<td class="gt_row gt_center" headers="(1)">0.058***</td>
<td class="gt_row gt_center" headers="(2)">0.058***</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" "></td>
<td class="gt_row gt_center" headers="(1)">p = &lt;0.001</td>
<td class="gt_row gt_center" headers="(2)">p = &lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" " style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000"></td>
<td class="gt_row gt_center" headers="(1)" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000">s.e. = 0.014</td>
<td class="gt_row gt_center" headers="(2)" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000">s.e. = 0.014</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">Num.Obs.</td>
<td class="gt_row gt_center" headers="(1)">9024</td>
<td class="gt_row gt_center" headers="(2)">9024</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">R2</td>
<td class="gt_row gt_center" headers="(1)">0.599</td>
<td class="gt_row gt_center" headers="(2)">0.599</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">R2 Adj.</td>
<td class="gt_row gt_center" headers="(1)">0.597</td>
<td class="gt_row gt_center" headers="(2)">0.597</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">AIC</td>
<td class="gt_row gt_center" headers="(1)">10317.3</td>
<td class="gt_row gt_center" headers="(2)">10317.3</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">BIC</td>
<td class="gt_row gt_center" headers="(1)">10530.5</td>
<td class="gt_row gt_center" headers="(2)">10530.5</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">Log.Lik.</td>
<td class="gt_row gt_center" headers="(1)">-5128.658</td>
<td class="gt_row gt_center" headers="(2)">-5128.658</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers=" ">RMSE</td>
<td class="gt_row gt_center" headers="(1)">0.43</td>
<td class="gt_row gt_center" headers="(2)">0.43</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers=" ">Std.Errors</td>
<td class="gt_row gt_center" headers="(1)">IID</td>
<td class="gt_row gt_center" headers="(2)">HC3</td>
</tr>
</tbody><tfoot class="gt_sourcenotes">
<tr class="odd">
<td colspan="3" class="gt_sourcenote">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p>You can see that the variable region was not included in the output (this is because we already have dummies of north (not north = south), and central region). We may need to clean our dataset un some further steps.</p>
<p>Recall that one of the assumptions of a linear model is that errors are independent and identically distributed. We could run some tests to determine this, but with the contrast of the iid and robust errors (HC3) in the modelsummary output table we can already tell that this is not an issue/something to worry about in our estimations.</p>
<p>Besides the regression output table, we can can also visualise the magnitude and significance of the coefficients with a plot. The further away the variable (dot) marker is from the <span class="math inline">\(0\)</span> line, the larger the magnitude.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modelplot</span>(model1) <span class="sc">+</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">ifelse</span>(p.value <span class="sc">&lt;</span> <span class="fl">0.001</span>, <span class="st">"Significant"</span>, <span class="st">"Not significant"</span>)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"grey"</span>, <span class="st">"black"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                                 )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="predictionpolicy_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grey points indicate statistically insignificat (p&gt;0.001) coefficient estimates</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The scale of the plot is large due to the intercept estimate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Not unlike what we saw in out correlation matrix, household size, electricity, having a flush toilet… the magnitude of the impact of these variables on monthly per capita expenditure is significantly larger than that of other assets/predictors.</p>
</section>
<section id="performance-indicators" class="level4">
<h4 class="anchored" data-anchor-id="performance-indicators">Performance Indicators</h4>
<p>In predictive modelling, we are interested in the following performance metrics:</p>
<ul>
<li><p>Model <em>residuals</em>: recall residuals are the observed value minus the predicted value. We can estimate a model’s Root Mean Squared Error (RMSE) or the Mean Absolute Error (MAE). Residuals allow us to quantify the extent to which the predicted response value (for a given observation) is close to the true response value. Small RMSE or MAE values indicate that the prediction is close to the true observed value.</p></li>
<li><p>The <em>p-values</em>: represented by stars *** (and a pre-defined critical threshold, e.g.&nbsp;0.05), they point to the predictive power of each feature in the model; i.e.&nbsp;that the event does not occur by chance. In the same vein, the magnitude of the coefficient is also important, especially given that we are interested in explanatory power and not causality.</p></li>
<li><p>The <em>R-squared</em>: arguably the go-to indicator for performance assessment. Low R^2 values are not uncommon, especially in the social sciences. However, when hoping to use a model for predictive purposes, a low R^2 is a bad sign, large number of statistically significant features notwithstanding. The drawback from relying solely on this measure is that it does not take into consideration the problem of model over-fitting; i.e.&nbsp;you can inflate the R-squared by adding as many variables as you want, even if those variables have little predicting power. This method will yield great results in the training data, but will under perform when extrapolating the model to the test (or indeed any other) data set.</p></li>
</ul>
<p><strong><em>Residuals</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># = = Model Residuals = = #</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(model1<span class="sc">$</span>residuals))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-3.483927 -0.288657 -0.007872  0.000000  0.266950  1.887123 </code></pre>
</div>
</div>
<p>Recall that the residual is estimated as the true (observed) value minus the predicted value. Thus: the max(imum) error of 1.88 suggests that the model under-predicted expenditure by circa (log) $2 (or $6.5) for at least one observation. Fifty percent of the predictions (between the first and third quartiles) lie between (log) $0.28 and (log) $0.26 over the true value. From the estimation of the prediction residuals we obtain the popular measure of performance evaluation known as the Root Mean Squared Error (RMSE, for short).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the RMSE for the training dataset, or the in-sample RMSE.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Predict values on the training dataset</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, Train_df)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Obtain the errors (predicted values minus observed values of target variable)</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>error0 <span class="ot">&lt;-</span> p0 <span class="sc">-</span> Train_df[[<span class="st">"lnexp_pc_month"</span>]]</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. In-sample RMSE</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>RMSE_insample <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(error0 <span class="sc">^</span> <span class="dv">2</span>))</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(RMSE_insample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4271572</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TIP: Notice that the in-sample RMSE we have just estimated was also printed in the linear model (regression) output tables!</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The table printed with the stargazer package returns this value at the bottom, under the header Residual Std. Error (0.428)</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The table printed with the modelsummary package returns this value at the bottom, under the header RMSE (0.43), rounded up. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The RMSE (0.4271) gives us an absolute number that indicates how much our predicted values deviate from the true (observed) number. This is all in reference to the target vector (a.k.a. our outcome variable). Think of the question, <em>how far, on average, are the residuals away from zero?</em> Generally speaking, the lower the value, the better the model fit. Besides being a good measure of goodness of fit, the RMSE is also useful for comparing the ability of our model to make predictions on different (e.g.&nbsp;test) data sets. The in-sample RMSE should be close or equal to the out-of-sample RMSE.</p>
<p>In this case, our RMSE is ~0.4 units away from zero. Given the range of the target variable (roughly 4 to 11), the number seems to be relatively small and close enough to zero.</p>
<p><strong><em>P-values</em></strong></p>
<p>Recall the large number of statistically significant features in our model. The coefficient plot, where we indicate that statistical significance is defined by a p-value threshold of 0.001, a strict rule (given the popularity of the more relaxed 0.05 critical value), shows that only 4 out of 29 features/variables do not meet this criterion. We can conclude that the features we have selected are relevant predictors.</p>
<p><strong><em>R-squared</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(model1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnexp_pc_month ~ ., data = Train_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4839 -0.2887 -0.0079  0.2669  1.8871 

Coefficients: (2 not defined because of singularities)
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    7.978e+00  4.409e-02 180.945  &lt; 2e-16 ***
hhsize        -2.919e-01  6.429e-03 -45.397  &lt; 2e-16 ***
hhsize2        1.206e-02  4.811e-04  25.067  &lt; 2e-16 ***
agehead        2.749e-03  1.712e-03   1.606  0.10835    
agehead2      -4.168e-05  1.717e-05  -2.428  0.01519 *  
northNorth     8.001e-02  1.439e-02   5.560 2.78e-08 ***
central1       2.521e-01  1.023e-02  24.639  &lt; 2e-16 ***
rural1        -5.483e-02  1.687e-02  -3.250  0.00116 ** 
nevermarried1  2.706e-01  2.839e-02   9.533  &lt; 2e-16 ***
sharenoedu    -1.045e-01  2.006e-02  -5.212 1.91e-07 ***
shareread      7.514e-02  1.502e-02   5.004 5.72e-07 ***
nrooms         3.898e-02  4.032e-03   9.670  &lt; 2e-16 ***
floor_cement1  1.016e-01  1.742e-02   5.835 5.58e-09 ***
electricity1   3.718e-01  2.696e-02  13.793  &lt; 2e-16 ***
flushtoilet1   3.295e-01  3.263e-02  10.099  &lt; 2e-16 ***
soap1          2.150e-01  1.413e-02  15.220  &lt; 2e-16 ***
bed1           1.040e-01  1.297e-02   8.019 1.20e-15 ***
bike1          9.395e-02  1.064e-02   8.831  &lt; 2e-16 ***
musicplayer1   1.111e-01  1.451e-02   7.658 2.08e-14 ***
coffeetable1   1.369e-01  1.866e-02   7.338 2.36e-13 ***
iron1          1.302e-01  1.378e-02   9.455  &lt; 2e-16 ***
dimbagarden1   1.018e-01  1.017e-02  10.017  &lt; 2e-16 ***
goats1         7.964e-02  1.168e-02   6.820 9.68e-12 ***
dependratio   -4.501e-02  5.848e-03  -7.697 1.55e-14 ***
hfem1         -6.570e-02  1.238e-02  -5.307 1.14e-07 ***
grassroof1    -9.590e-02  1.575e-02  -6.089 1.18e-09 ***
mortarpestle1  3.288e-02  1.027e-02   3.200  0.00138 ** 
table1         5.074e-02  1.149e-02   4.417 1.01e-05 ***
clock1         5.840e-02  1.423e-02   4.103 4.11e-05 ***
regionNorth           NA         NA      NA       NA    
regionSouth           NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4278 on 8995 degrees of freedom
Multiple R-squared:  0.5986,    Adjusted R-squared:  0.5973 
F-statistic:   479 on 28 and 8995 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We have printed our model’s output once more, now using the r base command summary(). The other packages (stargazer and modelsummary) are great if you want to export your results in text, html, latex format, but not necessary if you just want to print your output. The estimated (Multiple) R-squared of 0.59 tells us that our model predicts around 60 per cent of the variation in the independent variable (our target, log of per capita monthly expenditures). Also note that when we have a large number of predictors, it’s best to look at the Adjusted R-squared (of 0.59), which corrects or adjusts for this by only increasing when a new feature improves the model more so than what would be expected by chance.</p>
</section>
<section id="out-of-sample-predictions" class="level4">
<h4 class="anchored" data-anchor-id="out-of-sample-predictions">Out of sample predictions</h4>
<p>Now that we have built and evaluated our model in the training dataset, we can proceed to make out-of-sample predictions. That is, see how our model performs in the test dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, Test_df)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="do">### Observed summary statistics of target variable in full dataset</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(data_malawi<span class="sc">$</span>lnexp_pc_month))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.777   6.893   7.305   7.359   7.758  11.064 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Predictions based on the training dataset</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(p0))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  6.011   6.980   7.308   7.357   7.661  10.143 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Predictions from the testing dataset</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  6.052   6.999   7.323   7.375   7.670   9.774 </code></pre>
</div>
</div>
<p>The summary statistics for the predictions with the train and test datasets are very close to one another. This is an indication that our model extrapolates well to other datasets. Compared to the observed summary statistics of the target variable, they’re relatively close, with the largest deviations observed at the minimum and maximum values.</p>
</section>
<section id="the-bias-variance-tradeoff-in-practice" class="level4">
<h4 class="anchored" data-anchor-id="the-bias-variance-tradeoff-in-practice">The bias-variance tradeoff in practice</h4>
<p>We previously mentioned that the RMSE metric could also be used to compare between train and test model predictions. Let us estimate the out-of-sample RMSE:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>error <span class="ot">&lt;-</span> p <span class="sc">-</span> Test_df[[<span class="st">"lnexp_pc_month"</span>]] <span class="co"># predicted values minus actual values</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>RMSE_test <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(error<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(RMSE_test) <span class="co"># this is known as the out-of-sample RMSE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4284404</code></pre>
</div>
</div>
<p>Notice that the <em>in-sample RMSE</em> [<span class="math inline">\(0.4271572\)</span>] is very close to the <em>out-of-sample RMSE</em> [<span class="math inline">\(0.4284404\)</span>]. This means that our model makes consistent predictions across different data sets. We also know by now that these predictions are relatively good. At least, we hit the mark around 60 per cent of the time. What we are observing here is a model that has found a balance between bias and variance. However, both measures can still improve. For one, McBride and Nichols (2018) report &gt; 80 per cent accuracy in their poverty predictions for Malawi. But please note that, at this point, we are not replicating their approach. They document using a classification model, which means that they previously used a poverty line score and divided the sample between individuals below and above the poverty line.</p>
<p><em>What do we mean by bias in a model?</em></p>
<p>The bias is the difference between the average prediction of our model and the true (observed) value. Minimising the bias is analogous to minimising the RMSE.</p>
<p><em>What do we mean by variance in a model?</em></p>
<p>It is the observed variability of our model prediction for a given data point (how much the model can adjust given the data set). A model with high variance would yield low error values in the training data but high errors in the test data.</p>
<p>Hence, consistent in and out of sample RMSE scores = bias/variance balance.</p>
</section>
<section id="fine-tuning-model-parameters" class="level4">
<h4 class="anchored" data-anchor-id="fine-tuning-model-parameters">Fine-tuning model parameters</h4>
<p>Can we fine-tune model parameters? The quick answer is yes! Every algorithm has a set of parameters that can be adjusted/fine-tuned to improve our estimations. Even in the case of a simple linear model, we can try our hand at fine-tuning with, for example, cross-validation.</p>
<p><em>What is cross-validation?</em></p>
<p>Broadly speaking, it is a technique that allows us to assess the performance of our machine learning model. How so? Well, it looks at the ‘stability’ of the model. It’s a measure of how well our model would work on new, unseen data (is this ringing a bell yet?); i.e.&nbsp;it has correctly observed and recorded the patterns in the data and has not captured too much noise (what we know as the error term, or what we are unable to explain with our model). K-fold cross-validation is a good place to start for such a thing. In the words of <a href="https://www.javatpoint.com/cross-validation-in-machine-learning">The Internet™</a>, what k-fold cross validation does is:</p>
<pre><code>Split the input dataset into K groups
    For each group:
        - Take one group as the reserve or test data set.
        - Use remaining groups as the training dataset.
        - Fit the model on the training set and evaluate the performance of the model using the test set.</code></pre>
<p>TL;DR We’re improving our splitting technique!</p>
<p>An Illustration by <a href="https://eugenia-anello.medium.com/">Eugenia Anello</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/kfold_crossvalidation.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's rumble! </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create an object that defines the training method as cross-validation and number of folds (caret pkg)</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>cv_10fold <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"cv"</span>, <span class="co">#cross-validation</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">number =</span> <span class="dv">10</span> <span class="co"># k-fold = 10-fold (split the data into 10 similar-sized samples)</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a><span class="co"># train a model </span></span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>ols_kfold <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>    lnexp_pc_month <span class="sc">~</span> .,</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Train_df,</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">'lm'</span>, <span class="co"># runs a linear regression model (or ols)</span></span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">trControl =</span> cv_10fold <span class="co"># use 10 folds to cross-validate</span></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a>ols_kfold2 <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a>    lnexp_pc_month <span class="sc">~</span> .,</span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> Test_df,</span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">'lm'</span>, <span class="co"># runs a linear regression model (or ols)</span></span>
<span id="cb45-24"><a href="#cb45-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">trControl =</span> cv_10fold <span class="co"># use 10 folds to cross-validate</span></span>
<span id="cb45-25"><a href="#cb45-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-26"><a href="#cb45-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-27"><a href="#cb45-27" aria-hidden="true" tabindex="-1"></a>ols_kfold3 <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb45-28"><a href="#cb45-28" aria-hidden="true" tabindex="-1"></a>    lnexp_pc_month <span class="sc">~</span> .,</span>
<span id="cb45-29"><a href="#cb45-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> data_malawi,</span>
<span id="cb45-30"><a href="#cb45-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">'lm'</span>, <span class="co"># runs a linear regression model (or ols)</span></span>
<span id="cb45-31"><a href="#cb45-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">trControl =</span> cv_10fold <span class="co"># use 10 folds to cross-validate</span></span>
<span id="cb45-32"><a href="#cb45-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-33"><a href="#cb45-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-34"><a href="#cb45-34" aria-hidden="true" tabindex="-1"></a><span class="do">### Linear model with train dataset</span></span>
<span id="cb45-35"><a href="#cb45-35" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ols_kfold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

9024 samples
  29 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 8121, 8121, 8123, 8122, 8121, 8121, ... 
Resampling results:

  RMSE       Rsquared   MAE      
  0.4295064  0.5947776  0.3365398

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Linear model with test dataset</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ols_kfold2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

2256 samples
  29 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 2030, 2030, 2030, 2030, 2031, 2031, ... 
Resampling results:

  RMSE       Rsquared   MAE      
  0.4312944  0.5991526  0.3379473

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Linear model with full dataset")</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ols_kfold3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

11280 samples
   29 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 10152, 10152, 10152, 10152, 10152, 10152, ... 
Resampling results:

  RMSE       Rsquared   MAE      
  0.4291473  0.5965825  0.3363802

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
</div>
<p>Having cross-validated our model with 10 folds, we can see that the results are virtually the same. We have a RMSE of around .43, an R^2 of .59, (and a MAE of .33). We ran the same model for the train, test and full datasets and find results are consistent. Recall the R^2 tells us the model’s predictive ability and the RMSE and MAE the model’s accuracy.</p>
<p><strong>NOTE:</strong> k-fold cross-validation replaces our original 80/20 split (we don’t need to do that anymore!) Therefore, we use the full dataset in the train() function. Using the train, test and full datasets in the example above was just for pedagogical purposes but it is no longer necessary and we can use the reported estimates of R^2 (close to 1!), RMSE (close to 0!) and MAE (let’s go low!) for model assessment without comparing them to another set of predictions. These reported parameters are estimated as the average of the R^2, RMSE, and MAE for all the folds.</p>
</section>
</section>
<section id="feature-selection-with-lasso-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="feature-selection-with-lasso-linear-regression">4. Feature selection with Lasso linear regression</h3>
<p>An OLS regression is not the only model that can be written in the form of <span class="math inline">\(Y_i = \alpha + \beta_1X_{1i}, \beta_2X_{2i},..., \beta_pX_{pi}+ u_i\)</span>. In this section we will discuss ‘penalised’ models, which can also be expressed as a linear relationship between parameters. Penalised regression models are also known as regression shrinkage methods, and they take their name after the colloquial term for coefficient regularisation, ‘shrinkage’ of estimated coefficients. The goal of penalised models, as opposed to a traditional linear model, is not to minimise bias (least squares approach), but to reduce variance by adding a constraint to the equation and effectively pushing coefficient parameters towards 0. This results in the the worse model predictors having a coefficient of zero or close to zero.</p>
<p>Consider a scenario where you have hundreds of predictors. Which covariates are truly important for our known outcome? Including all of the predictors leads to <em>over-fitting</em>. We’ll find that the R^2 value is high, and conclude that our in-sample fit is good. However, this may lead to bad out-of-sample predictions. <em>Model selection</em> is a particularly challenging endeavour when we encounter high-dimensional data; i.e.&nbsp;when the number of variables is close to or larger than the number of observations. Some examples where you may encounter high-dimensional data include:</p>
<ol type="1">
<li><p>Cross-country analyses: we have a small and finite number of countries, but we may collect/observe as many variables as we want.</p></li>
<li><p>Cluster-population analyses: we wish to understand the outcome of some unique population <span class="math inline">\(n\)</span>, e.g.&nbsp;all students from classroom A. We collect plenty of information on these students, but the sample and the population are analogous <span class="math inline">\(n = N\)</span>, and thus the sample number of observations is small and finite.</p></li>
</ol>
<p>The LASSO - Least Absolute Shrinkage and Selection Operator imposes a shrinking penalty to those predictors that do not actually belong in the model, and reduces the size of the estimated <span class="math inline">\(\beta\)</span> coefficients towards and including zero (when the tuning parameter/ shrinkage penalty <span class="math inline">\(\lambda\)</span> is sufficiently large). Note that <span class="math inline">\(lambda\)</span> is the penalty term called <em>L1-norm</em>, and corresponds to the sum of the absolute coefficients.</p>
<p>What does this mean for our case? Well, McBride and Nichols (2018) used two sources to compile their final dataset (which we are using). One of those sources is the Living Standards Measurement Study (<a href="https://www.worldbank.org/en/programs/lsms">LSMS</a>) from the World Bank Group. These surveys collect more than 500 variables/ features per country case. You can subset the dataset with critical reasoning: using your knowledge of the phenomenon, which features might best describe it? But even then, we might still end up with a large number of features. Perhaps a LASSO approach could work here.</p>
<p>Our own data is not ideal for the approach, because it has a small number of features (<span class="math inline">\(29\)</span>), compared to the large number of observations (<span class="math inline">\(11,280\)</span>). But let’s run a lasso regression and see if my statement holds. How would I know if it holds? If the Lasso regression returns the same values for the performance assessment parameters as the OLS regression; this means that the penalisation parameter was either zero (leading back to an OLS) or too small to make a difference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">### small detour ... </span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnexp_pc_month ~ ., data = Train_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4839 -0.2887 -0.0079  0.2669  1.8871 

Coefficients: (2 not defined because of singularities)
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    7.978e+00  4.409e-02 180.945  &lt; 2e-16 ***
hhsize        -2.919e-01  6.429e-03 -45.397  &lt; 2e-16 ***
hhsize2        1.206e-02  4.811e-04  25.067  &lt; 2e-16 ***
agehead        2.749e-03  1.712e-03   1.606  0.10835    
agehead2      -4.168e-05  1.717e-05  -2.428  0.01519 *  
northNorth     8.001e-02  1.439e-02   5.560 2.78e-08 ***
central1       2.521e-01  1.023e-02  24.639  &lt; 2e-16 ***
rural1        -5.483e-02  1.687e-02  -3.250  0.00116 ** 
nevermarried1  2.706e-01  2.839e-02   9.533  &lt; 2e-16 ***
sharenoedu    -1.045e-01  2.006e-02  -5.212 1.91e-07 ***
shareread      7.514e-02  1.502e-02   5.004 5.72e-07 ***
nrooms         3.898e-02  4.032e-03   9.670  &lt; 2e-16 ***
floor_cement1  1.016e-01  1.742e-02   5.835 5.58e-09 ***
electricity1   3.718e-01  2.696e-02  13.793  &lt; 2e-16 ***
flushtoilet1   3.295e-01  3.263e-02  10.099  &lt; 2e-16 ***
soap1          2.150e-01  1.413e-02  15.220  &lt; 2e-16 ***
bed1           1.040e-01  1.297e-02   8.019 1.20e-15 ***
bike1          9.395e-02  1.064e-02   8.831  &lt; 2e-16 ***
musicplayer1   1.111e-01  1.451e-02   7.658 2.08e-14 ***
coffeetable1   1.369e-01  1.866e-02   7.338 2.36e-13 ***
iron1          1.302e-01  1.378e-02   9.455  &lt; 2e-16 ***
dimbagarden1   1.018e-01  1.017e-02  10.017  &lt; 2e-16 ***
goats1         7.964e-02  1.168e-02   6.820 9.68e-12 ***
dependratio   -4.501e-02  5.848e-03  -7.697 1.55e-14 ***
hfem1         -6.570e-02  1.238e-02  -5.307 1.14e-07 ***
grassroof1    -9.590e-02  1.575e-02  -6.089 1.18e-09 ***
mortarpestle1  3.288e-02  1.027e-02   3.200  0.00138 ** 
table1         5.074e-02  1.149e-02   4.417 1.01e-05 ***
clock1         5.840e-02  1.423e-02   4.103 4.11e-05 ***
regionNorth           NA         NA      NA       NA    
regionSouth           NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4278 on 8995 degrees of freedom
Multiple R-squared:  0.5986,    Adjusted R-squared:  0.5973 
F-statistic:   479 on 28 and 8995 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># notice that region dummies are repeated and therefore return NA in the output. We should clean this before proceeding.</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># these guys are troublesome (recall our conversation about zero-variance predictors?)</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>data_malawi2 <span class="ot">&lt;-</span> data_malawi[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">colnames</span>(data_malawi)<span class="sc">==</span><span class="st">"region"</span>)]</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(lnexp_pc_month<span class="sc">~</span>., <span class="at">data =</span> data_malawi2)) <span class="co"># no more excluded categorical variables (recall this happened in our original linear model due to repeated measures?)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lnexp_pc_month ~ ., data = data_malawi2)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.6626 -0.2906 -0.0096  0.2665  1.8788 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    7.965e+00  3.947e-02 201.781  &lt; 2e-16 ***
hhsize        -2.979e-01  5.854e-03 -50.893  &lt; 2e-16 ***
hhsize2        1.246e-02  4.401e-04  28.307  &lt; 2e-16 ***
agehead        3.545e-03  1.529e-03   2.319 0.020433 *  
agehead2      -5.079e-05  1.532e-05  -3.315 0.000918 ***
northNorth     7.452e-02  1.292e-02   5.766 8.32e-09 ***
central1       2.552e-01  9.119e-03  27.979  &lt; 2e-16 ***
rural1        -5.488e-02  1.507e-02  -3.642 0.000272 ***
nevermarried1  2.416e-01  2.507e-02   9.638  &lt; 2e-16 ***
sharenoedu    -1.053e-01  1.802e-02  -5.845 5.21e-09 ***
shareread      7.838e-02  1.344e-02   5.832 5.63e-09 ***
nrooms         4.182e-02  3.609e-03  11.587  &lt; 2e-16 ***
floor_cement1  9.460e-02  1.546e-02   6.119 9.73e-10 ***
electricity1   3.719e-01  2.387e-02  15.579  &lt; 2e-16 ***
flushtoilet1   3.471e-01  2.886e-02  12.027  &lt; 2e-16 ***
soap1          2.163e-01  1.261e-02  17.154  &lt; 2e-16 ***
bed1           1.051e-01  1.156e-02   9.099  &lt; 2e-16 ***
bike1          9.405e-02  9.516e-03   9.883  &lt; 2e-16 ***
musicplayer1   1.090e-01  1.287e-02   8.466  &lt; 2e-16 ***
coffeetable1   1.311e-01  1.641e-02   7.991 1.47e-15 ***
iron1          1.325e-01  1.231e-02  10.761  &lt; 2e-16 ***
dimbagarden1   9.140e-02  9.095e-03  10.049  &lt; 2e-16 ***
goats1         8.671e-02  1.049e-02   8.269  &lt; 2e-16 ***
dependratio   -4.086e-02  5.225e-03  -7.820 5.74e-15 ***
hfem1         -6.761e-02  1.102e-02  -6.135 8.80e-10 ***
grassroof1    -9.138e-02  1.394e-02  -6.556 5.77e-11 ***
mortarpestle1  3.207e-02  9.193e-03   3.489 0.000487 ***
table1         5.132e-02  1.029e-02   4.987 6.23e-07 ***
clock1         6.254e-02  1.273e-02   4.912 9.16e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4278 on 11251 degrees of freedom
Multiple R-squared:  0.5997,    Adjusted R-squared:  0.5987 
F-statistic: 601.9 on 28 and 11251 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>cv_10fold <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"cv"</span>, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">number =</span> <span class="dv">10</span> </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>model_lasso <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>    lnexp_pc_month <span class="sc">~</span> .,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> data_malawi,</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">'lasso'</span>,</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>), <span class="co">#This will first center and then scale all relevant variables in the model</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">trControl =</span> cv_10fold <span class="co"># use 10 folds to cross-validate // we already know this fine-tuning may not be needed!</span></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_lasso) <span class="co"># best R^2 and RMSE is similar to the one using a linear regression...( and so is the MAE!)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The lasso 

11280 samples
   29 predictor

Pre-processing: centered (30), scaled (30) 
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 10152, 10152, 10152, 10152, 10152, 10152, ... 
Resampling results across tuning parameters:

  fraction  RMSE       Rsquared   MAE      
  0.1       0.5953796  0.4234291  0.4653872
  0.5       0.4485973  0.5660193  0.3533998
  0.9       0.4295497  0.5957600  0.3368464

RMSE was used to select the optimal model using the smallest value.
The final value used for the model was fraction = 0.9.</code></pre>
</div>
</div>
<section id="parameter-tuning-in-our-lasso-regression" class="level4">
<h4 class="anchored" data-anchor-id="parameter-tuning-in-our-lasso-regression">Parameter-tuning in our Lasso regression</h4>
<p>Let’s start with centering and scaling variables; why do we do that?</p>
<p><em>Centering and Scaling in Lasso</em>: Recall that the L1-norm puts constraints on the size of the coefficients of the Lasso regression. The size, of course, differs based on the different scales the variables are measured. Having <span class="math inline">\(1\)</span> and up to <span class="math inline">\(55\)</span> electric gadgets at home is not the same as earning between <span class="math inline">\(1000\)</span> and <span class="math inline">\(100,000\)</span> monthly (of whichever currency you want to imagine here). There are two immediate consequences of centering and scaling (or normalising). 1) There is no longer an intercept. 2) It is easier to rank the relative magnitude of the coefficients post-shrinkage.</p>
<p><em>Cross-validation in Lasso:</em> Beyond training and testing dataframes, what a k-fold (commonly 10-fold) cross validation does is resample the data to find an optimal (λ) lambda/penalisation for the lasso model and assess its predictive error. Recall: The optimal λ (lambda)/penalisation minimizes the out-of-sample (or test) mean prediction error.</p>
<p>This tuning is already included in the chunk of code above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's visualise our lasso model:</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_lasso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="predictionpolicy_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The x-axis is the fraction of the full solution (i.e., ordinary least squares with no penalty)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The x-axis is the fraction of the full solution (i.e., ordinary least squares with no penalty)</code></pre>
</div>
</div>
<p>It seems that the fraction used (0.9) is close to the non-penalised model (or OLS/linear). Our original claim that this particular set-up does not call for a Lasso approach was correct. We may want to try other machine learning algorithms to see if we can improve our initial predictions!</p>
<p>A final note: there is some discussion over whether k-fold or really any cross-validation technique is optimal for choosing the lambda parameter in Lasso models (see for example, this Coursera <a href="https://www.coursera.org/lecture/ml-regression/choosing-the-penalty-strength-and-other-practical-issues-with-lasso-SPr8p">video</a>). It is true that cross-validation is something that we want to do for ALL our machine learning models. Just make sure to make an informed choice of which cv technique you’ll implement in your model.</p>
<p><strong>A setup with multiple categorical variables is problematic with Lasso!</strong></p>
<p>Lasso models do not perform well with multiple categorical variables. As is our case. Primarily because, in order to work with categorical data in lasso models we encode them as dummies (for example, north = <span class="math inline">\(1\)</span> and <span class="math inline">\(0\)</span> otherwise, center = <span class="math inline">\(1\)</span> and <span class="math inline">\(0\)</span> otherwise). Lasso will thus only consider the dummy, and not the concept of the ‘region’). An alternative to that is a Group Lasso. If you’d like to read more on that, you can have a look at this <a href="https://towardsdatascience.com/beyond-linear-regression-467a7fc3bafb#:~:text=Lasso%20feature%20selection%20works%20well,with%20few%20non%2Dzero%20coefficients.">Towards Data Science Post</a>.</p>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>At this point, our best predictions are made with a linear regression algorithm, which bested a lasso model. As we progress, we will explore other common machine learning algorithms to see whether our prediction capabilities improve!.</p>
</section>
<section id="practice-at-home" class="level2">
<h2 class="anchored" data-anchor-id="practice-at-home">Practice at home</h2>
<p>You can replicate the exercises in Python or R using the Malawi dataset. However, if you’d like a challenge, you can also try running a Linear and a Lasso Linear model using a similar dataset for the country of Bolivia. The dataset was put together by McBride and Nichols for the same paper for which they used the Malawi dataset.</p>
<p><a class="btn btn-primary" download="" href="data/bolivia.csv"> Download Bolivia df CSV </a></p>
</section>
<section id="readings" class="level2">
<h2 class="anchored" data-anchor-id="readings">Readings</h2>
<p><em>Mandatory</em></p>
<ul>
<li><p>An introduction to Statistical learning, Chapter 2, 3 (Regression), 5 (Cross-validation) and 6 (for more about Lasso).</p></li>
<li><p>Athey, S. (2017). <a href="https://www.science.org/doi/10.1126/science.aal4321">Beyond prediction: Using big data for policy problems</a>. Science, 355(6324), 483-485.</p></li>
<li><p>Kleinberg, J., Ludwig, J., Mullainathan, S. and Obermeyer, Z., 2015. <a href="https://www.aeaweb.org/articles?id=10.1257/aer.p20151023">Prediction policy problems. American Economic Review</a>, 105(5), pp.491-95.</p></li>
</ul>
<p><em>Optional readings</em></p>
<ul>
<li><p>Kleinberg, J., Lakkaraju, H., Leskovec, J., Ludwig, J. and Mullainathan, S., 2017. <a href="https://academic.oup.com/qje/article-abstract/133/1/237/4095198?redirectedFrom=fulltext">Human decisions and machine predictions.</a> The Quarterly Journal of Economics, 133(1), pp.237-293.</p></li>
<li><p>Hanna, R., &amp; Olken, B. A. (2018). <a href="https://www.aeaweb.org/articles?id=10.1257/jep.32.4.201">Universal basic incomes versus targeted transfers: Anti-poverty programs in developing countries.</a> Journal of Economic Perspectives, 32(4), 201-26. (exercise application)</p></li>
<li><p>McBride, L., &amp; Nichols, A. (2018). <a href="https://academic.oup.com/wber/article-abstract/32/3/531/2447896?redirectedFrom=fulltext">Retooling poverty targeting using out-of-sample validation and machine learning.</a> The World Bank Economic Review, 32(3), 531-550.pter 5.1</p></li>
</ul>
<!--DISQUS COMMENTS SCRIPT-->
<div id="disqus_thread">

</div>
<script>
    var disqus_config = function () {
    this.page.identifier = "predictionpolicy.html"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://unu-merit.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>
Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>


</section>

<div class="footer">
Copyright © 2025 Michelle González Amador &amp; Stephan Dietrich. All rights reserved.<br> <a href="https://github.com/michelleg06/Machine-Learning-for-Public-Policy"><img src="https://img.shields.io/badge/GitHub-Repository-blue?logo=github.png" class="img-fluid" alt="GitHub"></a>
</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>